"""Demo dataset tooling.

    python examples/demo-data/build_demo_db.py            # build demo.db from demo.sql
    python examples/demo-data/build_demo_db.py --regen    # regenerate demo.sql (synthetic data)

demo.sql is portable between SQLite and PostgreSQL. All data is synthetic and
deterministic (fixed seed); it describes a made-up online shop.
"""

from __future__ import annotations

import argparse
import random
import sqlite3
from datetime import date, timedelta
from pathlib import Path

HERE = Path(__file__).parent
SQL_FILE = HERE / "demo.sql"

SCHEMA = """\
CREATE TABLE customers (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  region TEXT NOT NULL,
  signup_date DATE NOT NULL
);
CREATE TABLE products (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC(10, 2) NOT NULL
);
CREATE TABLE orders (
  id INTEGER PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customers (id),
  product_id INTEGER NOT NULL REFERENCES products (id),
  quantity INTEGER NOT NULL,
  order_date DATE NOT NULL
);
"""

REGIONS = ["North America", "Europe", "Asia Pacific", "Latin America"]
PRODUCTS = [
    ("Notebook A5", "Stationery", 4.50), ("Fountain Pen", "Stationery", 18.00),
    ("Desk Lamp", "Home Office", 32.90), ("Monitor Stand", "Home Office", 45.00),
    ("Ergonomic Chair", "Home Office", 219.00), ("Mechanical Keyboard", "Electronics", 89.00),
    ("Wireless Mouse", "Electronics", 24.99), ("USB-C Hub", "Electronics", 39.50),
    ("Noise-Cancelling Headphones", "Electronics", 149.00), ("Tote Bag", "Accessories", 12.00),
    ("Water Bottle", "Accessories", 15.50), ("Sticker Pack", "Accessories", 3.25),
]  # fmt: skip
FIRST = ["Ava", "Liam", "Noah", "Mia", "Zoe", "Ethan", "Ivy", "Leo", "Nina", "Omar", "Sana", "Yuki"]
LAST = ["Kim", "Garcia", "Silva", "Novak", "Tanaka", "Okafor", "Meyer", "Rossi", "Lopez", "Chen"]


def generate_sql() -> str:
    rng = random.Random(42)
    lines = [
        "-- Synthetic demo data for DataLake Canvas. Generated by build_demo_db.py --regen.",
        SCHEMA,
    ]
    customers = []
    for cid in range(1, 41):
        signup = date(2023, 1, 1) + timedelta(days=rng.randrange(0, 365))
        name = f"{rng.choice(FIRST)} {rng.choice(LAST)}"
        customers.append(cid)
        lines.append(
            f"INSERT INTO customers VALUES ({cid}, '{name}', '{rng.choice(REGIONS)}', '{signup}');"
        )
    for pid, (name, category, price) in enumerate(PRODUCTS, start=1):
        lines.append(f"INSERT INTO products VALUES ({pid}, '{name}', '{category}', {price:.2f});")
    for oid in range(1, 601):
        day = date(2024, 1, 1) + timedelta(days=rng.randrange(0, 366))
        lines.append(
            f"INSERT INTO orders VALUES ({oid}, {rng.choice(customers)}, "
            f"{rng.randrange(1, len(PRODUCTS) + 1)}, {rng.randrange(1, 6)}, '{day}');"
        )
    return "\n".join(lines) + "\n"


def build_db(path: Path) -> None:
    path.unlink(missing_ok=True)
    conn = sqlite3.connect(path)
    try:
        conn.executescript(SQL_FILE.read_text())
        conn.commit()
    finally:
        conn.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument("--regen", action="store_true", help="rewrite demo.sql")
    parser.add_argument("--out", type=Path, default=HERE / "demo.db", help="SQLite output path")
    args = parser.parse_args()
    if args.regen:
        SQL_FILE.write_text(generate_sql())
        print(f"wrote {SQL_FILE}")
    build_db(args.out)
    print(f"built {args.out}")
